name: Fixed Azure Deployment - DISABLED

# DISABLED - Use deploy-simple.yml instead
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:  # Manual trigger only

env:
  AZURE_WEBAPP_NAME: microlearn-backend
  NODE_VERSION: '18.x'

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install dependencies'
      run: npm ci

    - name: 'Check if publish profile secret exists'
      run: |
        if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
          echo "❌ ERROR: AZURE_WEBAPP_PUBLISH_PROFILE secret is not set!"
          echo "Please add this secret in GitHub Settings → Secrets and Variables → Actions"
          echo "Download publish profile from Azure Portal → Your App Service → Get publish profile"
          exit 1
        else
          echo "✅ Publish profile secret found"
        fi

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'
        slot-name: 'production'
